### ISSUE TITLE
Console can't run slimecustomizer commands

### ISSUE THREAD

**Issue by Overseer9** [NCBPFluffyBear/SlimeCustomizer#5]
## Description (Required)
Console can't run command, like any command
but run normally when run by player

## Steps to reproduce the Issue (Required)
- open console
- run command "slimecustomizer" or "slimecustomizer getsaveditem 0 name 1"

## Expected behavior (Required)
- the commands works the same when ran by player in the server

## Server Log / Error Report
![image](https://user-images.githubusercontent.com/81430883/114020967-be507580-98a2-11eb-93aa-f8a4e935dc21.png)

## Environment (Required)
![image](https://user-images.githubusercontent.com/81430883/114021513-5cdcd680-98a3-11eb-8bf6-90c129ab4076.png)

![image](https://user-images.githubusercontent.com/81430883/114021587-6f571000-98a3-11eb-97c0-0cd3818c2cdd.png)

**Comment by NCBPFluffyBear** [comment]
Oops I thought I replied to this already...

I not going to consider this an urgent issue for now, especially since you aren't supposed to run that command in console anyways. I'll bundle a fix for this along with the next SC update, but until then, just don't use that command in console (It's not like you need to anyways).

**Comment by Overseer9** [comment]
yeah not a problem
I need SC to be able to run from the console so I can give rewards to players automatically from crates

buy I have itembridge plugin covered that problem

**Comment by NCBPFluffyBear** [comment]
Ah I see, I think I'm going to be releasing some new features soon so I'll bundle the fix in with that.
